### ISSUE TITLE
Segunda tutoría grupo 2

### ISSUE THREAD

**Issue by Jonathan-vt** [Jonathan-vt/Restaurant_App#10]

**Comment by Maes2109** [comment]
El día 27 de octubre a la hora de 7:30pm a 8:00pm segunda tutoría con los integrantes Jonathan Valenzuela, Jimmy Salcedo y María Alejandra Escalante junto con el Tutor Wilson Andres Castillo. Se presenta el avance que llevamos con el grupo hasta el momento que es el login Y la interfaz de lo que es la primera pantalla para presentar la aplicación, se atienden a todas las correcciones y sugerencias que hace el tutor en compañía del líder de equipo y dos de los acompañantes. A las 8:09 pm finalización de la tutoría 

La compañera Alda Ortega se ausenta por motivos de salud.
La compañera Yolanda Alvarez se encontraba en transporte publico.

**Comment by Maes2109** [comment]
![image](https://user-images.githubusercontent.com/111828043/198439691-e18832e3-2ce8-417e-8ada-9a82fa67c70c.jpeg)
