### ISSUE TITLE
primera tutoría grupo 2

### ISSUE THREAD

**Issue by Jonathan-vt** [Jonathan-vt/Restaurant_App#9]

**Comment by alluor22** [comment]
El día jueves 20 de octubre a las 7:30 el equipo de desarrollo se reune con el tutor Wilson Andres Castillo Castro, para aclar dudas sobre el inicio del proyecto, el tutor indica como realizar la conexión del proyecto Restaurante de Android Studio con GitHub

**Comment by alluor22** [comment]
Asistentes a la primera tutoría:
Jonathan Valenzuela
Maria Alejandra Escalante
Jimmy Orlando Salcedo
Yolanda Alvarez
Alda Lucía Ortega

**Comment by alluor22** [comment]
![Screenshot_20221015-164912](https://user-images.githubusercontent.com/116392308/197295586-533c4f23-006e-4a5b-9950-ade5f6363724.png)
